fix CI .env variable

diff --git a/.github/workflows/android-appium.yml b/.github/workflows/android-appium.yml
--- a/.github/workflows/android-appium.yml
+++ b/.github/workflows/android-appium.yml
@@ -59,5 +59,15 @@ jobs:
           emulator-options: -no-snapshot-load -no-snapshot-save -no-boot-anim -no-audio -memory 4096 -port 5554 -wipe-data -feature -Vulkan -gpu host -accel on -no-metrics -writable-system -verbose -skin 440x960 -gpu swiftshader_indirect -feature BluetoothEmulation=off -no-window
           emulator-boot-timeout: 300
           script: |
-            echo "Emulator started"
+            echo "Emulator started ✅"
+
+            # 🟩 Проверяем путь до ADB
+            echo "ANDROID_HOME=$ANDROID_HOME"
+            ls -la $ANDROID_HOME/platform-tools || echo "platform-tools not found!"
+            $ANDROID_HOME/platform-tools/adb version || echo "ADB not found!"
+
+            # 🟩 Проверим, что эмулятор доступен по ADB
+            $ANDROID_HOME/platform-tools/adb devices
+
+            # 🟩 Запуск тестов
             pytest -s
